name: medusa_admin_dart_client
description: A new Flutter package project.
version: 0.1.2
homepage:

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  freezed_annotation: ^3.1.0
  retrofit: ^4.1.0
  get_it: ^8.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.0
  retrofit_generator: ^10.0.2
  json_serializable: ^6.11.0

flutter: